SELECT FLAVOR 
FROM (
    SELECT FLAVOR, SUM(TOT) TOD
    FROM(
        SELECT FLAVOR, SUM(TOTAL_ORDER) TOT
        FROM FIRST_HALF
        GROUP BY FLAVOR
        UNION ALL 
        SELECT FLAVOR,SUM(TOTAL_ORDER) TOT
        FROM JULY
        GROUP BY FLAVOR
    )
    GROUP BY FLAVOR    
    ORDER BY TOD DESC
)
WHERE ROWNUM <= 3 